version: '3.8'

x-env: &env
  TZ: ${TZ:-Europe/Moscow}
  WAIT_HOSTS: mysql:3306
  WAIT_TIMEOUT: 60
  DB_DSN: ${DB_DSN}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}

x-app: &app
  init: true
  restart: unless-stopped
  logging:
    options:
      max-size: "100k"
      max-file: "1"

services:
  check_email:
    <<: *app
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: build
    environment:
      <<: *env
      MEMORY: ${EMAIL_CHECK_MEMORY}
      BATCH: ${EMAIL_CHECK_BATCH}
      DELAY: ${EMAIL_CHECK_DELAY}
      VERBOSE: ${VERBOSE:-0}
    depends_on:
      - mysql
    command: ["/app/bin/check_email"]
    deploy:
      mode: replicated
      replicas: ${EMAIL_CHECK_THREADS}
      resources:
        limits:
          cpus: '0.50'
          memory: 10M
        reservations:
          cpus: '0.25'
          memory: ${EMAIL_CHECK_MEMORY}

  cron:
    <<: *app
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: cron
    container_name: cron-karma-test
    environment:
      <<: *env
      EMAIL_SEND_DELAY: ${EMAIL_SEND_DELAY}
      EMAIL_SEND_BATCH: ${EMAIL_SEND_BATCH}
      EMAIL_SEND_MEMORY_LIMIT: ${EMAIL_SEND_MEMORY_LIMIT}
      EMAIL_SEND_PERIOD_DAYS: ${EMAIL_SEND_PERIOD_DAYS}
      EMAIL_SEND_THREADS: ${EMAIL_SEND_THREADS}
      VERBOSE: ${VERBOSE:-0}
    depends_on:
      - mysql
